spring.application.name=bff-agendador-tarefas
server.port=8083

usuario.url=localhost:8080/usuario
agendador-tarefas.url=localhost:8081/tarefas
notificacao.url=localhost:8082/email

cron.horario=0 */5 * * * ?

usuario.email=edsonviniciussouza2006@gmail.com
usuario.senha=1234
